function [fitresult, gof] = createFit(x1, x2, y)
%CREATEFIT(X1,X2,Y)
%  Create a fit.
%
%  Data for 'perfect3Fit2b' fit:
%      X Input : x1
%      Y Input : x2
%      Z Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 31-Aug-2017 10:25:57


%% Fit: 'perfect3Fit2b'.
[xData, yData, zData] = prepareSurfaceData( x1, x2, y );

% Set up fittype and options.
ft = fittype( 'poly33' );

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft );

% Plot fit with data.
figure( 'Name', 'perfect3Fit2b' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'perfect3Fit2b', 'y vs. x1, x2', 'Location', 'NorthEast' );
% Label axes
xlabel x1
ylabel x2
zlabel y
grid on
view( -1.9, 2.0 );


